Updated ip for use with rpi3b
ole-vi/pirateship pull request #14
Opened 2017-06-22 00:28 UTC by snazzybunny

Instructions on how to install are found in README.md. It would be a good idea to find a way to include the npm plugins like commander and underscore as well as nodejs v8 into the image, that is, if we were to use this program. Otherwise, you would need Internet before being able to use this program.

Tested on rpi3:
default, detectrpi, swifi, wifi, rename

Needs work on rpi3:
sethernet, expandfs

2017-06-22 00:51 UTC, snazzybunny commented
If we can install node and its dependencies on treeimage builder that would be good. I assume we can include the npm plugins with the ip program so the user doesnt need Internet to download them.

2017-06-27 04:05 UTC, dogi requested changes
please change following

2017-06-27 04:05 UTC, dogi commented on README.md
> +    sethernet <ip> <mask> <gateway> <dns>                      configures rpi ethernet interface to a static ip address
@snazzybunny please do not remove old subcommands

2017-06-27 04:05 UTC, dogi commented on lib/DetectRPI.js
> +    "a02082" : "RPI3B"
@snazzybunny we should also add comments for raspberry pi zero and pi zero W, so that other maybe fill this gaps ...

2017-07-12 21:42 UTC, dogi approved these changes

2017-07-12 21:43 UTC, merged